export { AUTOMATION_ACTIONS } from './header';
export { AUTOMATION_SPELLS, AUTOMATION_ADDITIONS } from './catalog';
export type { AutomationAddition } from './catalog';
export type { AutomationOptions, SpellVariantDef } from './variants';
export { SPELL_VARIANTS, spellVariantDef } from './variants';
export { shadowBladeReturnAction, spellBuiltinAutomated } from './builders';
export { automationForSpell, automationForAction, spellEffectDefs, spellTempHp, spellDamageParts, spellAutomated, spellByDesign, spellWeaponOverride } from './derive';
export type { ActionAutomationOptions } from './derive';
export { AUTOMATION_SPECS } from './specs';
export { compileSpec, resolveSpec, validateSpec } from './compile';
export type { ActionSpec, AutomationSpec, AutomationSpecCopy, ChoiceSpec, EffectSpec, LoadoutSpec, ValueExpr, WeaponAttackSpec } from './spec';
