export { AUTOMATION_ACTIONS } from './header';
export type { AutomationOptions, SpellVariantDef } from './variants';
export { spellVariantDef } from './variants';
export { shadowBladeReturnAction } from './helpers';
export { automationForSpell, automationForAction, spellTempHp, spellDamageParts, spellAutomated, spellByDesign, spellWeaponOverride } from './derive';
export type { ActionAutomationOptions } from './derive';
export { AUTOMATION_SPECS } from './specs';
export { compileSpec, resolveSpec, validateSpec } from './compile';
export { materializeAutomation, materializeSpell } from './materialize';
export type { MaterializedAutomation, SpellAuto, SpellDef } from './materialize';
export type { ActionSpec, AutomationSpec, AutomationSpecCopy, ChoiceSpec, EffectSpec, LoadoutSpec, ManualSpec, SummonSpec, ValueExpr, WeaponAttackSpec } from './spec';
